# Project information
site_name: LM_NLP_NEP_Project
# defeine TOC or order of website-
nav:
  - Home: index.md

site_author: Lalit Mohan
site_description: >-
  DESCRIPTION

# Repository
repo_name: lmohan171/LM_NLP_NEP_Project
repo_url: https://github.com/lmohan171/LM_NLP_NEP_Project

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lmohan171
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LalitMo97574047
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lalit-mohan-b8a17b14/
    
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="lmohan171/LM_NLP_NEP_Project"  target="_blank" rel="noopener"> Lait Mohan</a>